<a href="https://colab.research.google.com/github/harada26009/TU_M_Math/blob/main/Chap06_Ex6-6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

%precision 3

'%.3f'

練習問題6-4

In [18]:
data4 = {
    'id': ['0','1','2','3','4','6','8','11','12','13'],
    'city': ['Tokyo','Osaka','Kyoto','Hokkaido','Tokyo','Tokyo','Osaka','Kyoto','Hokkaido','Tokyo'],
    'birth_year': [1990,1989,1992,1997,1982,1991,1988,1990,1995,1981],
    'name': ['Hiroshi','Akiko','Yuki','Satoru','Steeve','Mituru','Aoi','Tarou','Suguru','Mitsuo']
}
df4 = DataFrame(data4)
df4

   id      city  birth_year     name
0   0     Tokyo        1990  Hiroshi
1   1     Osaka        1989    Akiko
2   2     Kyoto        1992     Yuki
3   3  Hokkaido        1997   Satoru
4   4     Tokyo        1982   Steeve
5   6     Tokyo        1991   Mituru
6   8     Osaka        1988      Aoi
7  11     Kyoto        1990    Tarou
8  12  Hokkaido        1995   Suguru
9  13     Tokyo        1981   Mitsuo

In [24]:
data6 = {
    'id': ['70','80','90','120','150'],
    'city': ['Chiba','Kanagawa','Tokyo','Fukuoka','Okinawa'],
    'birth_year': [1980,1999,1995,1994,1994],
    'name': ['Suguru','Kouichi','Satochi','Yukie','Akari']
}
df6 = DataFrame(data6)
df6

    id      city  birth_year     name
0   70     Chiba        1980   Suguru
1   80  Kanagawa        1999  Kouichi
2   90     Tokyo        1995  Satochi
3  120   Fukuoka        1994    Yukie
4  150   Okinawa        1994    Akari

In [25]:
concat_data = pd.concat([df4,df6])
concat_data

    id      city  birth_year     name
0    0     Tokyo        1990  Hiroshi
1    1     Osaka        1989    Akiko
2    2     Kyoto        1992     Yuki
3    3  Hokkaido        1997   Satoru
4    4     Tokyo        1982   Steeve
5    6     Tokyo        1991   Mituru
6    8     Osaka        1988      Aoi
7   11     Kyoto        1990    Tarou
8   12  Hokkaido        1995   Suguru
9   13     Tokyo        1981   Mitsuo
0   70     Chiba        1980   Suguru
1   80  Kanagawa        1999  Kouichi
2   90     Tokyo        1995  Satochi
3  120   Fukuoka        1994    Yukie
4  150   Okinawa        1994    Akari