<a href="https://colab.research.google.com/github/harada26009/TU_M_Math/blob/main/Chap06_Ex6-15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

%precision 3

'%.3f'

In [26]:
from numpy import nan as NA

df  = pd.DataFrame(np.random.rand(10,4))

df.iloc[1,0] = NA
df.iloc[2:3,2] = NA
df.iloc[5:,3] = NA

In [27]:
df

          0         1         2         3
0  0.267825  0.603909  0.865673  0.786346
1       NaN  0.893343  0.446580  0.774142
2  0.521421  0.396124       NaN  0.525610
3  0.881833  0.230740  0.160419  0.242151
4  0.589298  0.274954  0.813821  0.147995
5  0.316221  0.767159  0.927949       NaN
6  0.094784  0.099682  0.459000       NaN
7  0.208298  0.185173  0.957162       NaN
8  0.284251  0.850131  0.829711       NaN
9  0.998005  0.010792  0.941508       NaN

In [29]:
df2 = pd.DataFrame(np.random.rand(15,6))

df2.iloc[2,0] = NA
df2.iloc[5:8,2] = NA
df2.iloc[7:9,3] = NA
df2.iloc[10,5] = NA

df2

           0         1         2         3         4         5
0   0.664968  0.518279  0.021683  0.826750  0.919220  0.026244
1   0.240211  0.769624  0.627443  0.374184  0.820944  0.163123
2        NaN  0.039805  0.885070  0.969993  0.321158  0.052704
3   0.017823  0.609962  0.900113  0.340352  0.889808  0.772925
4   0.864023  0.258882  0.192435  0.771240  0.857856  0.319642
5   0.297787  0.707261       NaN  0.477413  0.987536  0.998381
6   0.180520  0.960476       NaN  0.899567  0.165803  0.031884
7   0.599386  0.466413       NaN       NaN  0.539945  0.932621
8   0.984042  0.552130  0.280379       NaN  0.564428  0.103302
9   0.705067  0.710331  0.023104  0.727814  0.975710  0.392705
10  0.701887  0.883611  0.054966  0.846101  0.260966       NaN
11  0.117652  0.706570  0.220969  0.301240  0.285236  0.822108
12  0.448700  0.351072  0.360536  0.447492  0.196668  0.855287
13  0.537223  0.000532  0.723204  0.121652  0.375962  0.696245
14  0.014793  0.296343  0.901604  0.311368  0.535008  0.680480

In [30]:
df2.dropna()

           0         1         2         3         4         5
0   0.664968  0.518279  0.021683  0.826750  0.919220  0.026244
1   0.240211  0.769624  0.627443  0.374184  0.820944  0.163123
3   0.017823  0.609962  0.900113  0.340352  0.889808  0.772925
4   0.864023  0.258882  0.192435  0.771240  0.857856  0.319642
9   0.705067  0.710331  0.023104  0.727814  0.975710  0.392705
11  0.117652  0.706570  0.220969  0.301240  0.285236  0.822108
12  0.448700  0.351072  0.360536  0.447492  0.196668  0.855287
13  0.537223  0.000532  0.723204  0.121652  0.375962  0.696245
14  0.014793  0.296343  0.901604  0.311368  0.535008  0.680480

In [31]:
df2.fillna(0)

           0         1         2         3         4         5
0   0.664968  0.518279  0.021683  0.826750  0.919220  0.026244
1   0.240211  0.769624  0.627443  0.374184  0.820944  0.163123
2   0.000000  0.039805  0.885070  0.969993  0.321158  0.052704
3   0.017823  0.609962  0.900113  0.340352  0.889808  0.772925
4   0.864023  0.258882  0.192435  0.771240  0.857856  0.319642
5   0.297787  0.707261  0.000000  0.477413  0.987536  0.998381
6   0.180520  0.960476  0.000000  0.899567  0.165803  0.031884
7   0.599386  0.466413  0.000000  0.000000  0.539945  0.932621
8   0.984042  0.552130  0.280379  0.000000  0.564428  0.103302
9   0.705067  0.710331  0.023104  0.727814  0.975710  0.392705
10  0.701887  0.883611  0.054966  0.846101  0.260966  0.000000
11  0.117652  0.706570  0.220969  0.301240  0.285236  0.822108
12  0.448700  0.351072  0.360536  0.447492  0.196668  0.855287
13  0.537223  0.000532  0.723204  0.121652  0.375962  0.696245
14  0.014793  0.296343  0.901604  0.311368  0.535008  0.680480

In [33]:
df2.mean()

0    0.455292
1    0.522086
2    0.432626
3    0.570397
4    0.579750
5    0.489118
dtype: float64

In [35]:
df2.fillna(df2.mean())

           0         1         2         3         4         5
0   0.664968  0.518279  0.021683  0.826750  0.919220  0.026244
1   0.240211  0.769624  0.627443  0.374184  0.820944  0.163123
2   0.455292  0.039805  0.885070  0.969993  0.321158  0.052704
3   0.017823  0.609962  0.900113  0.340352  0.889808  0.772925
4   0.864023  0.258882  0.192435  0.771240  0.857856  0.319642
5   0.297787  0.707261  0.432626  0.477413  0.987536  0.998381
6   0.180520  0.960476  0.432626  0.899567  0.165803  0.031884
7   0.599386  0.466413  0.432626  0.570397  0.539945  0.932621
8   0.984042  0.552130  0.280379  0.570397  0.564428  0.103302
9   0.705067  0.710331  0.023104  0.727814  0.975710  0.392705
10  0.701887  0.883611  0.054966  0.846101  0.260966  0.489118
11  0.117652  0.706570  0.220969  0.301240  0.285236  0.822108
12  0.448700  0.351072  0.360536  0.447492  0.196668  0.855287
13  0.537223  0.000532  0.723204  0.121652  0.375962  0.696245
14  0.014793  0.296343  0.901604  0.311368  0.535008  0.680480