<a href="https://colab.research.google.com/github/harada26009/TU_M_Math/blob/main/Chap06_Ex6-5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

%precision 3

'%.3f'

練習問題6-4

In [18]:
data4 = {
    'id': ['0','1','2','3','4','6','8','11','12','13'],
    'city': ['Tokyo','Osaka','Kyoto','Hokkaido','Tokyo','Tokyo','Osaka','Kyoto','Hokkaido','Tokyo'],
    'birth_year': [1990,1989,1992,1997,1982,1991,1988,1990,1995,1981],
    'name': ['Hiroshi','Akiko','Yuki','Satoru','Steeve','Mituru','Aoi','Tarou','Suguru','Mitsuo']
}
df4 = DataFrame(data4)
df4

   id      city  birth_year     name
0   0     Tokyo        1990  Hiroshi
1   1     Osaka        1989    Akiko
2   2     Kyoto        1992     Yuki
3   3  Hokkaido        1997   Satoru
4   4     Tokyo        1982   Steeve
5   6     Tokyo        1991   Mituru
6   8     Osaka        1988      Aoi
7  11     Kyoto        1990    Tarou
8  12  Hokkaido        1995   Suguru
9  13     Tokyo        1981   Mitsuo

In [19]:
data5 = {
    'id': ['0','1','3','6','8'],
    'math': [20,30,50,70,90],
    'english': [30,50,50,70,20],
    'sex': ['M','F','F','M','M'],
    'index_num': [0,1,2,3,4]
}
df5 = DataFrame(data5)
df5

  id  math  english sex  index_num
0  0    20       30   M          0
1  1    30       50   F          1
2  3    50       50   F          2
3  6    70       70   M          3
4  8    90       20   M          4

In [23]:
pd.merge(df4, df5, how = 'outer')

   id      city  birth_year     name  math  english  sex  index_num
0   0     Tokyo        1990  Hiroshi  20.0     30.0    M        0.0
1   1     Osaka        1989    Akiko  30.0     50.0    F        1.0
2  11     Kyoto        1990    Tarou   NaN      NaN  NaN        NaN
3  12  Hokkaido        1995   Suguru   NaN      NaN  NaN        NaN
4  13     Tokyo        1981   Mitsuo   NaN      NaN  NaN        NaN
5   2     Kyoto        1992     Yuki   NaN      NaN  NaN        NaN
6   3  Hokkaido        1997   Satoru  50.0     50.0    F        2.0
7   4     Tokyo        1982   Steeve   NaN      NaN  NaN        NaN
8   6     Tokyo        1991   Mituru  70.0     70.0    M        3.0
9   8     Osaka        1988      Aoi  90.0     20.0    M        4.0